export default [
  {
    fullName: 'Alice Morgan',
    occupation: 'Software Engineer',
    department: 'Engineering',
    employmentDate: '2023-01-15',
    terminationDate: null,
  },
  {
    fullName: 'Ben Jackson',
    occupation: 'Marketing Specialist',
    department: 'Marketing',
    employmentDate: '2025-06-01',
    terminationDate: null,
  },
  {
    fullName: 'Chloe Thompson',
    occupation: 'Data Analyst',
    department: 'Analytics',
    employmentDate: '2022-03-10',
    terminationDate: '2025-12-01',
  },
  {
    fullName: 'Daniel Wu',
    occupation: 'HR Manager',
    department: 'Human Resources',
    employmentDate: '2019-09-05',
    terminationDate: '2024-11-30',
  },
  {
    fullName: 'Ella Rivera',
    occupation: 'UX Designer',
    department: 'Design',
    employmentDate: '2025-07-20',
    terminationDate: '2025-12-31',
  },
  {
    fullName: 'Francis Scott',
    occupation: 'Project Manager',
    department: 'Engineering',
    employmentDate: '2020-06-12',
    terminationDate: null,
  },
  {
    fullName: 'Gina Wheeler',
    occupation: 'Sales Manager',
    department: 'Sales',
    employmentDate: '2021-08-22',
    terminationDate: null,
  },
  {
    fullName: 'Henry Adams',
    occupation: 'Software Developer',
    department: 'Engineering',
    employmentDate: '2018-02-15',
    terminationDate: '2024-08-15',
  },
  {
    fullName: 'Isabella Lee',
    occupation: 'Financial Analyst',
    department: 'Finance',
    employmentDate: '2023-05-10',
    terminationDate: null,
  },
  {
    fullName: 'Jack Mitchell',
    occupation: 'Customer Support',
    department: 'Support',
    employmentDate: '2022-11-04',
    terminationDate: null,
  },
  {
    fullName: 'Karen Harris',
    occupation: 'Product Designer',
    department: 'Design',
    employmentDate: '2024-02-19',
    terminationDate: '2026-02-19',
  },
  {
    fullName: 'Liam Smith',
    occupation: 'Network Administrator',
    department: 'IT',
    employmentDate: '2019-05-01',
    terminationDate: null,
  },
  {
    fullName: 'Monica Green',
    occupation: 'Marketing Specialist',
    department: 'Marketing',
    employmentDate: '2021-07-10',
    terminationDate: '2024-07-10',
  },
  {
    fullName: 'Nathan Brown',
    occupation: 'Content Writer',
    department: 'Marketing',
    employmentDate: '2022-09-13',
    terminationDate: null,
  },
]
