export default [
  {
    id: 1,
    fullName: 'Alice Morgan',
    occupation: 'Software Engineer',
    department: 'Engineering',
    employmentDate: '2023-01-15',
    terminationDate: null,
  },
  {
    id: 2,
    fullName: 'Ben Jackson',
    occupation: 'Marketing Specialist',
    department: 'Marketing',
    employmentDate: '2025-06-01',
    terminationDate: null,
  },
  {
    id: 3,
    fullName: 'Clara Evans',
    occupation: 'HR Manager',
    department: 'Human Resources',
    employmentDate: '2022-09-10',
    terminationDate: '2024-11-01',
  },
  {
    id: 4,
    fullName: 'David Lee',
    occupation: 'Data Analyst',
    department: 'Data Science',
    employmentDate: '2021-06-18',
    terminationDate: null,
  },
  {
    id: 5,
    fullName: 'Ella Thompson',
    occupation: 'UI/UX Designer',
    department: 'Product Design',
    employmentDate: '2020-02-03',
    terminationDate: '2023-07-12',
  },
  {
    id: 6,
    fullName: 'Francisco Gómez',
    occupation: 'Backend Developer',
    department: 'Engineering',
    employmentDate: '2024-03-20',
    terminationDate: null,
  },
  {
    id: 7,
    fullName: 'Grace Lin',
    occupation: 'QA Tester',
    department: 'Quality Assurance',
    employmentDate: '2019-11-05',
    terminationDate: null,
  },
  {
    id: 8,
    fullName: 'Hassan Ibrahim',
    occupation: 'DevOps Engineer',
    department: 'Infrastructure',
    employmentDate: '2022-01-22',
    terminationDate: null,
  },
  {
    id: 9,
    fullName: 'Isabella Rossi',
    occupation: 'Project Manager',
    department: 'Operations',
    employmentDate: '2020-08-14',
    terminationDate: '2024-04-30',
  },
  {
    id: 10,
    fullName: 'Jonas Berg',
    occupation: 'Financial Analyst',
    department: 'Finance',
    employmentDate: '2021-03-11',
    terminationDate: null,
  },
  {
    id: 11,
    fullName: 'Karen Müller',
    occupation: 'Customer Support Agent',
    department: 'Customer Service',
    employmentDate: '2023-06-09',
    terminationDate: null,
  },
  {
    id: 12,
    fullName: 'Liam O’Connor',
    occupation: 'Security Officer',
    department: 'Security',
    employmentDate: '2018-10-01',
    terminationDate: '2023-12-31',
  },
  {
    id: 13,
    fullName: 'Maria Silva',
    occupation: 'Content Strategist',
    department: 'Marketing',
    employmentDate: '2024-05-07',
    terminationDate: null,
  },
  {
    id: 14,
    fullName: 'Noah Kim',
    occupation: 'Machine Learning Engineer',
    department: 'Data Science',
    employmentDate: '2022-04-01',
    terminationDate: null,
  },
  {
    id: 15,
    fullName: 'Olivia Dubois',
    occupation: 'Legal Advisor',
    department: 'Legal',
    employmentDate: '2020-12-17',
    terminationDate: null,
  },
]
